# -*- coding: utf-8 -*-
"""1 - Kurulum ve Başlangıç.ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMnIWKQfEPc5a7ARuSp2WgaEPCTHX3hs

---

# 📊 Python ile Veri Analizine Giriş  
## ⚙️ Kurulum Yönergesi

---

Bu defter, Python ile veri analizi yapabilmek için gerekli **çalışma ortamının nasıl kurulacağını** anlatmaktadır.

### 📌 İçerik:
- 🧪 Jupyter Defterleri  
- 🐍 Anaconda  
- ☁️ Google Colab

---
# 1. Yazılım Kurulumu

Bu defter, ilerleyen oturumlar için temel hazırlık niteliğindedir.  
Ders boyunca en güncel Python sürümü (şu anda **>=3.9**) ile çalışacağız ve **Jupyter Notebook** ortamını kullanacağız.

🔗 Python sürümlerine ulaşmak için: [https://www.python.org/downloads/](https://www.python.org/downloads/)

---

## 1.1. Python’u Bilgisayarınıza Kurun

Python’u doğrudan kendi bilgisayarınıza kurabilirsiniz. Aşağıdaki adımları izleyerek kurulumu tamamlayabilirsiniz:

1. Kurmak istediğiniz Python sürümünü seçin.  
2. **Python Yürütülebilir Kurulum Dosyası**nı (`.exe`) indirin ve çalıştırın.

### 💻 Windows Kullanıcıları için:

🔹 Kurulum sırasında **“Add Python to PATH”** seçeneğini işaretlemeyi unutmayın.  
🔹 Eğer `pip` veya `python` komutları komut satırında çalışmıyorsa, manuel olarak **PATH** değişkenine eklemeniz gerekebilir.

**Nasıl yapılır?**

- `python.exe` ve `pip.exe` dosyalarının bulunduğu klasörün yolunu kopyalayın:  
  `C:\Users\kullanici_adiniz\AppData\Local\Programs\Python\Python310\Scripts`
- Denetim Masası → Sistem ve Güvenlik → Sistem → Gelişmiş Sistem Ayarları → Ortam Değişkenleri  
- “Path” değişkenini seçin → **Düzenle → Yeni** diyerek klasör yolunu yapıştırın.

### 🍎 Mac Kullanıcıları için:

- macOS sisteminde Python’un önceden kurulu bir sürümü bulunur. Bu sürümler sistem tarafından kullanıldığı için **silinmemeli veya değiştirilmemelidir**.
- Yeni bir Python sürümü kurarsanız birden fazla Python sürümü olabilir.  
  Bu durumda hangi sürümün kullanılacağını dikkatli yönetmeniz gerekir.

🔗 Daha fazla bilgi: [https://docs.python.org/3/using/mac.html](https://docs.python.org/3/using/mac.html)

---

## 1.2. Python Dağıtım Aracı Olarak Anaconda Kullanımı

Alternatif olarak **Anaconda** adlı bir Python dağıtımını da tercih edebilirsiniz:  
🔗 [https://www.anaconda.com/products/individual](https://www.anaconda.com/products/individual)

🎯 Anaconda, veri bilimi için geliştirilmiş açık kaynaklı bir platformdur.  
İçerisinde çok sayıda kütüphane ve **Jupyter Notebook** hazır olarak gelir.

📺 Kurulum videosu: [YouTube: Anaconda Installation](https://www.youtube.com/watch?v=YJC6ldI3hWk)

🔽 Ek kurulum dosyaları:  
[https://www.anaconda.com/products/individual?modal=commercial#Downloads](https://www.anaconda.com/products/individual?modal=commercial#Downloads)

🗂️ Anaconda sürüm arşivi:  
[https://repo.anaconda.com/archive/](https://repo.anaconda.com/archive/)

---

## 1.3. Google Colab Kullanımı

Python’u yerel olarak kuramazsanız, **Google Colab** iyi bir alternatif olabilir.  
Google Colab, kurulum gerektirmeyen ve tamamen bulut tabanlı bir **Jupyter Notebook** ortamıdır.

✔️ Kod yazma, çalıştırma ve paylaşma işlemleri doğrudan tarayıcı üzerinden yapılabilir.  
✔️ Tek ihtiyacınız bir **Google** hesabıdır.

🔗 Google Colab: [https://colab.research.google.com](https://colab.research.google.com)

> 💡 Not: Mümkünse Python’u kendi bilgisayarınıza kurmanız (Yöntem 1 veya 2) şiddetle önerilir.

---

# 📓 2. Jupyter Defterleri Nasıl Kullanılır?


Jupyter defterlerini aşağıdaki yöntemlerle başlatabilirsiniz:

- 💻 **Windows** kullanıcıları: Başlat menüsündeki Jupyter simgesine tıklayarak  
- 🐧 **Linux** kullanıcıları: Terminale `jupyter-notebook` yazarak  
- 🚀 Ya da doğrudan **Anaconda Navigator** üzerinden

---

🎥 **Jupyter Defteri Başlatma ve Kullanım Videosu:**  
https://www.youtube.com/watch?v=HW29067qVWk

🛠️ **Kurulum Sorunları için Destek Kaynakları:**  
https://docs.continuum.io/anaconda/install

📚 **Jupyter / IPython Hızlı Başlangıç Kılavuzu:**  
http://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/

---

# 🐍 3. Python Temelleri

Jupyter Notebook ortamını kurduktan sonra, bu arayüzle tanışmanızı öneririz.  
Burası, çalıştırılabilir kod hücreleri içeren bir web sayfası gibidir.

▶️ **Kod hücrelerini çalıştırmak için** sol üstteki “Run” (çalıştır) düğmesine tıklayın (soldan 8. simge).  
💡 **Klavye kısayolları** ile çok daha hızlı çalışabilirsiniz: `'H'` tuşuna basarak tüm kısayolları görebilirsiniz.

---

🎥 **Giriş niteliğinde güzel bir video:**  
[https://www.youtube.com/watch?v=HW29067qVWk](https://www.youtube.com/watch?v=HW29067qVWk)

---

# 📦 4. İçe Aktarmalar (Imports)

Python’un –özellikle Anaconda dağıtımında sıkça kullanılan– en temel yapı taşlarından biri,  
**modül**, **paket** ya da **kütüphane** gibi ek bileşenleri mevcut betiğinize dahil edebilmektir.

Bu işlem, `import` komutu ile gerçekleştirilir.

```python
import numpy as np              # Sayısal işlemler için NumPy
import pandas as pd            # Veri analizi için Pandas
import matplotlib.pyplot as plt  # Görselleştirme için Matplotlib
"""

# pyhtonda "." bir objenin itip diğer objenin başladığını ifade eder.

math.log(36)

# yukarıdaki kod hata verdi çünkü math kütüphanesi yok. onu getirmedik. şimdi onu getirme işlemi.

import math

math.log(36)

math.pi

#pyhtondaki "=" işareti bir şeyi bir şeyin içine atamak demek matematikle aynı görevi görmez assign etmek daha çok.

pi_value = math.pi

#Mesela pi value artık math pi olan 3.14.... lı bir şey. Matematikteki eşittir pyhtondaki çift eşittire denk gelir "=="

math.cos(pi_value)

import math as mt

#Yukarıdaki işlemi yaparak math kütüphanesini "mt" olarak değiştirebilir ve artık mt olarak kullanabiliriz aşağıdaki gibi.

mt.log(36)

"""# 📝 Markdown Başlığı  
Bu bir markdown hücresidir. Kod çalıştırmaz.

# Markdown Hücresi Nedir?  
Bu hücreler, kod içermeyen metin açıklamaları yazmak için kullanılır.  
Başlıklar, listeler, bağlantılar ve formüller gibi yapılar markdown ile oluşturulabilir.
"""

#Tüm kütüphaneyi getirmek zorunda değilsin kütüphaneden ihtiyacın olan kısımları da getirebilirsin aşağıdaki gibi.

from statistics import mean, stdev
mean([22,45,30,156])

"""---

# 📚 5. Kütüphaneler / Paketler



Artık `import` komutunun temellerini öğrendiğinize göre, birden fazla kütüphane ve paketi kullanmaya alışmalıyız.

Python’da dış kütüphaneleri kurmak ve yönetmek için **pip** adlı bir paket yönetim sistemini kullanırız.

---

## 💻 Komut Satırına Erişim

Öncelikle, işletim sisteminize uygun **komut satırını (terminal)** açmalısınız:

- **Windows** kullanıcıları: Başlat menüsüne tıklayıp “cmd” aratın.
- **Mac** kullanıcıları: Spotlight (büyüteç) ile “terminal” aratın.

Açılan komut satırına aşağıdaki komutları yazarak ihtiyacınız olan paketleri kurabilirsiniz.  
Bu derste sıkça kullanacağımız bazı kütüphaneler:

```bash
pip install pandas
pip install matplotlib
pip install beautifulsoup4
pip install nltk
```
### 📌 Notlar

🔹 **Not 1:**  
Eğer bazı kütüphaneler yalnızca eski bir Python sürümüyle uyumluysa, ilgili Python sürümünü buradan indirip kurabilirsiniz:  
🌐 [https://www.python.org/downloads/](https://www.python.org/downloads/)

🔹 **Not 2:**  
Paket ya da yazılım kurulumu sırasında hata alırsanız, **yalnız değilsiniz** 😊  
İlk adım olarak sorunu Google’da aramayı deneyin.  
🧠 En yararlı kaynak genellikle [Stack Overflow](https://stackoverflow.com/) olacaktır —  
dünyanın en büyük ve en güvenilir yazılım geliştirici topluluğudur.


"""

pip install math

"""---

# 📖 6. Ek Kaynaklar


Python programlamaya yeni başlayanlar ve veri bilimiyle ilgilenenler için bazı yararlı çevrim içi kaynaklar aşağıda listelenmiştir:

### 🎓 Ücretsiz ve Online Kurslar:

- **Herkes için Programlama (Python’a Giriş)**  
  [https://www.coursera.org/learn/python?specialization=python](https://www.coursera.org/learn/python?specialization=python)

- **Python ile Uygulamalı Veri Bilimi**  
  [https://www.coursera.org/specializations/data-science-python](https://www.coursera.org/specializations/data-science-python)

- **MIT: Bilgisayar Bilimine ve Python ile Programlamaya Giriş**  
  [https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/)

- **MIT: Hesaplamalı Düşünme ve Veri Bilimine Giriş**  
  [https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0002-introduction-to-computational-thinking-and-data-science-fall-2016/](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0002-introduction-to-computational-thinking-and-data-science-fall-2016/)

---

### 📚 Başlangıç Seviyesinde Öğrenme Kaynakları:

- [A Whirlwind Tour of Python (Jake VanderPlas)](https://github.com/jakevdp/WhirlwindTourOfPython)  
- [Intro to Python (introtopython.org)](http://introtopython.org/)  
- [Jupyter Başlangıç Eğitimleri](https://github.com/jupyter/jupyter/wiki#introductory-tutorials)  
- [Python Resmi Dokümantasyonu (3.10)](https://docs.python.org/3.10/tutorial/index.html)  
- [Google Python Eğitimi](https://developers.google.com/edu/python)  
- [Awesome Python - Topluluk Tarafından Derlenen Kaynaklar](https://awesome-python.com/)

---

💡 Bu kaynaklar, Python öğrenme sürecinizi destekleyecek ve derinleştirecek şekilde seçilmiştir. Dilediğiniz sırayla inceleyebilirsiniz!

"""