# -*- coding: utf-8 -*-
"""Introduction to Python adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166k47utEYDK15WvRX-ERF3XF5qJLFp9h

---

# 📊 Programlamaya Giriş

---

**Python**, modern, güçlü ve dinamik bir programlama dilidir.  
Basit ve özlü bir sözdizimine sahiptir; öğrenmesi kolaydır, ancak nesne yönelimli programlama için son derece etkilidir.

Python yorumlayıcısı ve birçok gelişmiş kütüphane tamamen **ücretsiz** ve **açık kaynak** olarak sunulmaktadır.

Özellikle istatistikçiler ve bilgisayar bilimciler tarafından geliştirilen çok sayıda yararlı kütüphane sayesinde,  
Python veri analizi için ideal bir programlama dilidir.

---

## Bu Giriş Defteri Neyi Kapsıyor?

Bu giriş niteliğindeki defter, Python (veya herhangi bir programlama dili) ile ilgili temel kavramları adım adım açıklamaktadır.  
Her bölümü sırasıyla takip edin ve ilgili alıştırmaları çözerek ilerleyin:

1. **Ekrana Yazdırma (print)**  
2. **Değişkenler (variables)**  
3. **Listeler**  
4. **Karakter Dizileri (strings)**  
5. **Sözlükler (dictionaries)**  
6. **Operatörler**  
7. **Koşul İfadeleri ve Döngüler (if & loops)**  
8. **Fonksiyonlar**  
9. **Dosyalarla Çalışmak**

---

## Ekrana Yazdırma (print)

Haydi Python ile konuşmaya başlayalım!  
Diyelim ki ekrana bir mesaj yazdırmak istiyoruz. Bunu Python’a nasıl söyleriz? İşte "Hello World!" yazdırmak için bir satırlık Python kodu:

```python
print('Hello World')
"""

print("Hello World")

"""---

#### 💬 Yorum Satırları (Comments)

Python ile kod yazmaya başlar başlamaz, kodumuzu açıklamak için **yorum satırları** kullanmamız gerekir.  
Yorumlar, yazdığımız kodun ne yaptığını hem kendimize hem de başkalarına anlatmak için **son derece önemli ve faydalıdır**.

🔹 Yorum satırları, **#** sembolü ile başlar.

Bu şekilde Python, hangi satırların çalıştırılabilir olduğunu (yani yorum **olmayan**) ve hangi satırların sadece açıklama olduğunu (başında `#` olan) ayırt eder.

🧠 Kısacası, yorum satırları **insanlarla konuşur** (yani size veya kodu sonradan okuyacak bir başkasına),  
diğer satırlar ise **Python ile konuşur** (yani çalışan kodu oluşturur).

---

### Örnek:

```python
# Bu bir yorum satırıdır ve çalıştırılmaz
print("Merhaba Python!")  # Bu satır çalışır, ama sonundaki yorum kısmı çalıştırılmaz

"""

#hücreyi yandaki play tuşuna basarak da çalıştırabilirisn shift+enter yaparak da shift+enter yaparsan hem hücreyi çalıştırır hem de alta yeni kod satırı açar.

#istediğin hücre seçiliyken "A"ya basarsan üste yeni hücre açılır. Hiçbir şey çalıştırmadan sadece aşağıya hücre açmak istiyorsan hücre seçiliyken "B"e basarsın

# example comment, Python will ignore this line
print("Hello","My")
print("World")

"""---

#### `print()` Fonksiyonunda `sep` ve `end` Parametreleri

`print()` fonksiyonunun bazı varsayılan ayarları vardır:

- `sep=" "` → Elemanlar arasındaki ayırıcı (boşluk)
- `end="\n"` → Satır sonu karakteri (yeni satıra geç)

Bu değerleri isteğe göre değiştirebilirsiniz:

```python
print("merhaba", "dünya", sep="-", end="!")

"""

print("Hello", end="\n\n\n")   #3 tane end işareti ve "\n"ı koyduğu için 3 kere enter yapmış gibi çıktı verdi.
print("World")

print("Hello", "World", sep=" ")  #sep kısmıana boşlıuk koyduğu için bu şekilde ayırmış ama normalde de bunu yapmasa da o şekilde ayırıyor.

print("Hello", "World", sep="!")   #sep kısmına ünlem işareti koyduğu için ünlemle ayırmış.

print("Hello")
print("World")  # burada çıktı olarak vermesinin sebebi alt alta kodun yazılmış olması değil end olarak bir şey yapmasan veya demesen de aynı şekilde end olarak algılayıp aşağıya atıyor.

print("Hello", end="\n")
print("World")   #hiçbir şey yazmasan da yine aynı şey oluyor.

print("Hello", end="\n\n\n")
print("World")

print("Hello", end=" ")  #end olarak boşluk isteyince aşağıya atlamaka yerine wold'ü yanına yazdı.
print("World", end="!")

print("Ali","Ata","Bak",sep="!")

"""

## Değişkenler (Variables)


Değişkenler, bilgiyi (geçici olarak) saklamak için kullanılan **bellek alanlarıdır**.  
Bir değeri bilgisayarın hafızasında tutmanıza ve daha sonra o değere ulaşmanıza olanak sağlarlar.

---

### 📝 Değişken Tanımlamak: Değere Atama

Bir değişken tanımlamak için **atama işlemi** yapılır.

Atama işlemi şu şekilde gerçekleşir:

- Eşittir (`=`) işaretinin **solunda**, değişkenin adı yer alır.
- Sağ tarafında ise Python yorumlayıcısının anlayabileceği bir **ifade** olmalıdır.

```python
my_variable_integer = 100
"""

my_variable_integer = 100        # An integer assignment
my_variable_float = 1000.0       # A floating point
my_variable_string = "John3"      # A string

print(my_variable_integer)   #integer tam sayı değişkeni
print(my_variable_float)      #float kesirli sayı
print(my_variable_string)      # string metin aynı spssteki gibi. metni tırnak içinde yazarız.

"""---

### 🧾 Standart Değişken Türleri (Sınıfları)

Python'da her değişken, önceden tanımlanmış bir **veri tipine (sınıfa)** aittir.  
Bir değişken tanımladığınızda, Python yorumlayıcısına o değişkenin **hangi türde** olduğunu da söylemiş olursunuz:  
örneğin **tamsayı (integer)**, **ondalıklı sayı (float)** veya **metin (string)**.

Örneğin:

```python
my_int = 10           # integer (tamsayı)
my_float = 3.14       # float (ondalıklı sayı)
my_string = "Merhaba" # string (karakter dizisi)

"""

print(type(my_variable_string))

"""| Sınıf  | Örnek
|------|------
|   bool  |  True
|   int  | 5
|   float | 5.27836532
|   string | 'Hello World'

### Bir Değişkenin Adı
"""

# Example 1
x = 10
y = 12.5
z = x*y  #"*" yıldız işareti çarpma işlemi olarak yapılır.
print(z)

"""---

### Değişken İsimlendirme Kuralları

- Değişken ismi **harf ile başlamalıdır**.  
- Sonrasında harf, rakam veya `_` içerebilir.  
- **Büyük/küçük harf duyarlıdır**: `a` ve `A` farklıdır.

---
"""

# Example 2
number_of_students = 30
number_of_teachers = 12
number_of_students_and_teachers = number_of_students + number_of_teachers
print(number_of_students_and_teachers)

"""Değişken ismi seçerken okunabilirlik çok önemlidir. Hangisi daha anlaşılır? Umarım cevabınız örnek 2'dir!

Tavsiye: Küçük ‘l’, büyük ‘O’ ve büyük ‘I’ harflerini kullanmayın. Çünkü ‘l’ ve ‘I’, rakam olan 1’e çok benzer. ‘O’ ise 0’a benzer.

---

### 🔒 Rezerve Edilmiş Değişken İsimleri

Python'da değişken ismi olarak **sonsuz sayıda** isim seçebilirsiniz.  
Ancak bazı isimler **Python tarafından ayrılmıştır** ve değişken adı olarak kullanılamaz.

Bunlara **anahtar kelimeler (keywords)** denir. Örneğin: `if`, `for`, `while`, `class`, `import` gibi.

Bu isimler Python'un yapısal sözdiziminin bir parçasıdır ve **kendi özel işlevleri** vardır.

---

|Do|not|use|these|variable|names|in|Python
|--|--|--|--|--|--|--|--
|and|assert| break|exec| not| lambda|yield|with
|while|try| raise|print| pass| or| is| win
|import| if| global| from| for| finally|else|elif
|del|def|continue|class|return| True|False|except

---

### Alıştırmalar (Değişkenler)

Aşağıdaki değişkenleri oluşturun:

- Bir **string**: adı `_mystring` olsun ve `"LovePython"` değerini taşısın.  
- Bir **float (ondalıklı sayı)**: adı `_myfloat` olsun ve `6.0` değerini taşısın.  
- Bir **integer (tamsayı)**: adı `_myint` olsun ve `4` değerini taşısın.
"""

# change this code
mystring = "LovePython"
myfloat = 6.0
myint = 4

my_name = "Fuat"
print("Let's talk about %s." % my_name)  #yüzde işareti koyup string için "s" harfini gömüp istediğimiz string tipi değişkenini ekletebiliriz.

my_height = 1.78
print("He's", my_height, "meters tall")  #bu şekilde direkt yazdığı için bu şekilde yaptık. Yüzde işaretini kullanıyor olsaydık float tipinin fsini kullanırdık.

my_weight = 75
print("He's %i kg heavy." % my_weight)   #yüzde ile integer tipinin i'sini kullanmış.

print(f"{my_name}'s {my_weight} kg heavy.")  #f daha çok döngülerde göndereceğiz. birleştirme iççin kullanılmış bu kısımda.

"""---

## Listeler (Lists)

Python'da farklı veri tipleri bulunur. **Liste (list)**, en sık kullanılan veri tiplerinden biridir.  
Liste, birden fazla **değeri** bir arada tutan bir yapıdır ve köşeli parantez `[]` ile tanımlanır.

Bir listenin içindeki değerler farklı türlerde olabilir: **tamsayı (int)**, **ondalıklı sayı (float)**, **metin (string)** vb.  
Değerler arasında **virgül (`,`)** ile ayrılır.

### Örnekler:

```python
numbers = [1, 2, 3, 4]
mixed = [1, 2.5, "hello", True]
empty_list = []

"""

# empty list
my_list = []

# list of integers
my_list = [2, 5, 8, 9]   #listeleri yapmak için köşeli parantez içine listenin elemanlarını yazarsın.

# list of strings
my_list = [Monday', 'Tuesday', 'Wednesday', 8, 9']

my_list = list('Monday', 'Tuesday', 'Wednesday', 8, 9)  #list fonksiyonuyla da kendi listelerimizi oluşturabiliriz. ama bu çok istenen ve kullaılan bir yöntem değil.

"""---

### 📌 Listeler Üzerinde İşlemler

Listeler üzerinde birçok işlem yapılabilir:  
- Elemanlara erişme  
- Eleman ekleme veya silme  
- Sayısal listelerde matematiksel işlemler (çarpma, bölme, çıkarma vb.)

---

### 🔢 İndeksleme

Listelerdeki her bir elemana, **indeks** numarası ile ulaşılır.  
Python'da indeksler **0'dan başlar**.

Örneğin:

```python
my_list = ['Monday', 'Tuesday', 'Wednesday']
print(my_list[0])  # 'Monday'
#İndeks numarası listenin eleman numarası oluyor.

"""

# Declare a list of prime number
primes = [2,3,5,7,9,11]   #asal sayılar listesi

# Check the type of the varibale
type(primes)

# See the content of a list
print(primes)

# Check the length of a list
len(primes)  #listenin uzunluğunu hesaplamak için "len" komutu kullanılır. eleman sayısı

# Access one element
primes[5]  #primes listesinin 5. elemanını çağırma komutu verilmiştir burada.

# Modify an element
primes[5] = 13  #5. elemanı  13 ile değiştirme komutunu verdik.

primes

# Add an element at the end of the list
primes.append(17)   #append -> listeye yeni eleman ekleme komutu. 17 elemanını ekleme emri verdik
primes

# Deleting an element
del primes[6]  # del komutu delete komutunun kısaltılmışı bu komutla ve kod satırıyla listeden 6. elemanı çıkartma komutu verdik.
primes

primes_copy = primes

# add one elementt to primes
primes_copy.append(19)   #Muhtemelen primes_copy eşittir primes olduğu için ikisine de eklendi.

print('primes:', primes, ', primes_copy:', primes_copy)

"""⚠️ Yavaş! Ne Oldu Şimdi?

Listeleri kopyalarken dikkatli olmalısınız!  
Aşağıdaki gibi bir kopyalama sadece **yüzeysel bir kopya (shallow copy)** oluşturur:

Doğrusu ise şu şekilde:
"""

primes_copy = primes.copy()  #primes copy'i primes copy adlı bir değişkenin içine attık.

# add one elementt to primes
primes_copy.append(23)
print('primes:', primes, ', primes_copy:', primes_copy)  #bu neden bu şekide oldu araştır!!

"""Listelerde kullanılabilecek ilave fonksiyonlar:

**insert, extend, index, remove, sort, reverse, pop, ...**
"""

my_list = ['red', 'blue', 'yellow']

## insert 'black' at index 0
my_list.insert(2, 'black')
## add list of elems at end

my_list

new_list = ['gray', 'orange']

my_list.extend(new_list)
print(my_list)

"""### Alıştırmalar (Listeler)

1- Bir listedeki tüm öğelerin toplamını hesaplayan bir Python programı yazın.
"""

x = [1,2,5]
sum(x)

"""2- Bir listedeki en büyük ve en küçük sayıyı bulan bir Python programı yazın."""

print(min(x),max(x))

"""3- 10'dan küçük tamsayılardan oluşan bir liste oluşturun ve adını **a** koyun."""

a = [*range(10)]
a

"""---

## 📝 Karakter Dizileri (Strings)

Python'da string (karakter dizisi) tanımlamak için tek tırnak (`' '`) veya çift tırnak (`" "`) kullanılabilir.

Örneğin:
```python
a = "We Love Python!"

"""

a = "We Love Python!"

type(a)

len(a)

"""Python'da string'ler üzerinde kullanılabilecek birçok yerleşik fonksiyon vardır.
Örneğin, split() fonksiyonu bir string’i belirli bir ayırıcıya göre parçalara ayırır ve liste olarak döndürür.
"""

# Example: split the variable a to 3 words
print(a.split(' '))

# Example: append a string to another string
a = "We Love Python!"
b = "Python Loves Us!"
c = a + " & " + b
print(c)

len(c)

"""---

### Dilimleme ve İndeksleme

Önceki örneklerde indeksleme ve dilimleme işlemlerini kullandık.  
Bu bölümde bu iki yöntemin önemini vurgulayıp daha kapsamlı şekilde açıklıyoruz.

**İndeksleme**, bir dizi, liste veya string içindeki belirli bir elemana erişmeyi ifade eder.  
Örneğin `a` değişkenine geri dönersek, içindeki her karakterin bir indeksi vardır:

| Değişken `a` | W | e |   | L | o | v | e |   | P | y | t | h | o | n | ! |
|--------------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| İndeks       | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |10 |11 |12 |13 |14 |

Örneğin `'!'` karakteri **14. indekstedir**. Erişim şu şekilde yapılır:

```python
print(a[14])
```

### Negatif İndeksleme

Python'da **negatif indeksleme** de kullanılabilir.  
Bu, dizinin sonundan geriye doğru sayma anlamına gelir (pozitif indeksleme ise baştan sona doğrudur).

Negatif indeksleme özellikle uzun string, liste veya dizilerde sondaki bir elemana doğrudan erişmek istediğimizde kullanışlıdır.

| Değişken `a`     | W | e |   | L | o | v | e |   | P | y | t | h | o | n | ! |
|------------------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| Negatif İndeks   | -15 | -14 | -13 | -12 | -11 | -10 | -9 | -8 | -7 | -6 | -5 | -4 | -3 | -2 | -1 |

Örneğin `'!'` karakterine negatif indeks ile şu şekilde erişebilirsiniz:

```python
print(a[-1])  # çıktı: !

"""

# Example: access the character "!" in the variable a
print(a[-1])

"""Dilimleme, bir string (veya liste, dizi vb.) içinden bir karakter aralığını çağırmaktır.
Örneğin, a değişkeninden "Love" kısmını almak isteyebiliriz.
"""

# Example: print only "Love" part of the variable a
a = "We Love Python!"
print(a[3:7])

"""Ayrıca, belirli bir indeksten sona kadar ya da baştan belirli bir indekse kadar dilimleme de yapabiliriz:"""

# Example: slice the variable a from index 3 to the end
print(a[3:])

# Example: slice the variable a from the beginning till the index 7
print(a[:7])

"""Ayrıca karakterlere belirli bir adım (stride) aralığıyla da erişebiliriz. Örneğin:"""

# Example: acess every third charachter
print(a[0:14:3])

"""Genel olarak bir indeks yapısı [a:b:c] şeklindeyse,
a başlangıcı, b bitişi, c ise adım sayısını (step) belirtir.

Yukarıdaki örnekte tüm string’i yazdırdığımız için, başlangıç ve bitiş indekslerini atlayarak sadece iki nokta üst üste (::) ile aynı sonucu elde edebiliriz.
"""

# Example: acess every third charachter
print(a[::3])

"""---

## Sözlükler (Dictionaries)

Önceki bölümlerde Python listelerini ve ne kadar güçlü olduklarını öğrendik.  
Bu bölümde ise Python’daki başka bir veri tipi olan **sözlük (dictionary)** yapısını ele alacağız.

Sözlükler, Python’u güçlü ve etkili kılan veri yapılarındandır.  
Listeler gibi kolayca **değiştirilebilir**, çalışma sırasında **büyüyüp küçülebilir** ve bu işlemler için kopya oluşturmaya gerek yoktur.  
Ayrıca, bir sözlük içinde liste olabilir, bir liste içinde sözlükler olabilir.

---

### 🧱 Sözlük Tanımı

Bir sözlük, **küme parantezi `{}`** içine yazılmış, **virgülle ayrılmış anahtar-değer (key-value)** çiftleriyle tanımlanır.  
Her anahtar ile değeri arasında **iki nokta üst üste `:`** kullanılır:

```python
dic = {
    <anahtar1>: <değer1>,
    <anahtar2>: <değer2>,
    ...
    <anahtarN>: <değerN>
}

person = {
    "name": "Alice",
    "age": 30,
    "city": "Istanbul"
}
"""

Movie = {
  "name": "Twin Peaks",
  "director": "David Lynch",
  "year": 1990
}

"""Sözlük (dictionary) yapısında da, tıpkı listelerde olduğu gibi, elemanlara erişmek veya onları değiştirmek için çeşitli yöntemler vardır.  
Bir sözlükteki öğelere erişmek için `items()` veya `keys()` gibi metodlar kullanılabilir.

### Örnekler:

```python
person = {
    "name": "Alice",
    "age": 30,
    "city": "Istanbul"
}

print(person.keys())   # dict_keys(['name', 'age', 'city'])

print(person.items())  # dict_items([('name', 'Alice'), ('age', 30), ('city', 'Istanbul')])

```
"""

# keys() sözlükteki tüm anahtarları verir
print(Movie.keys())
# items() sözlükteki tüm tuple ikililerini (anahtar, değer) verir
print(Movie.items())

"""Sözlükleri değiştirmek için kullanılabilecek diğer bazı metodlar şunlardır:  
`get()`, `copy()`, `update()`, `pop()` vb.

Bu metodları daha iyi anlamak için aşağıdaki alıştırmaları yapın.

### Alıştırmalar (sözlükler)

1- `Movie` sözlüğündeki `"name"` anahtarının değerini `get` metodu ile yazdırın.
"""

Movie.get("name")

"""2- `Year` anahtarını 1990'dan 1991'e değiştirin."""

Movie["year"] = 1992

print(Movie)

"""3- `Movie` sözlüğüne `"genre": "mystery/drama/horror"` anahtar/değer çiftini ekleyin."""

Movie.update({"genre": "mystery/drama/horror"})
Movie

"""4- `Movie` sözlüğünden `"genre"` anahtarını `pop` metodu ile silin ve ekrana yazdırın."""

Movie.pop("genre")
Movie

"""---

## Kümeler ve Demetler (Sets ve Tuples)

Sözlükler ve listelere ek olarak, Python'da iki veri tipi daha vardır: **set (küme)** ve **tuple (demet)**.

- **Tuple**, birden fazla öğeyi tek bir değişkende saklamak için kullanılır.  
  Sıralıdır (**ordered**) ve değiştirilemez (**unchangeable**) bir yapıdır.

- **Set** ise sırasızdır (**unordered**).  
  Elemanları **benzersizdir**, yani aynı elemandan iki tane olamaz (**duplicate**'lar yasaktır).

---
"""

örnek_küme = set((3,4,5,6))

örnek_küme

örnek_küme = {3,4,5,6}

type(örnek_küme)

x = [0,3,7,3,7,4,4,5]

x = set(x)

x

string = "Python öğrenmek çok kolay!"

print(list(string))
print(set(string))

thistuple = ("apple", "banana", "cherry")
print(thistuple)

thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)

thistuple = ("apple", "banana", "cherry")
print(len(thistuple))

"""## Operatortörler

Python, birçok farklı türde operatörü destekler:  
**Aritmetik operatörler**, **mantıksal operatörler**, **karşılaştırma operatörleri** vb.

Bir **operatör**'ün ne olduğunu şöyle örnekleyebiliriz:

```python
12 * 7
Bu ifadede:

`*` → operatör

12 ve 7 → operand (üzerinde işlem yapılan değerler)

Aşağıda, özellikle veri analizi için önemli olan bazı operatör türlerini inceleyeceğiz.

### Aritmetik operatörler

Aritmetik operatörler, isminden de anlaşılacağı üzere sayılarla çalışır ve geleneksel cebirsel işlemleri kolayca yapmamızı sağlar.

| Operatör | Açıklama | Örnek |
|----------|----------|--------|
| `+` Toplama | Değerleri toplar | `a + b` |
| `-` Çıkarma | Sağdaki değeri soldakinden çıkarır | `a - b` |
| `*` Çarpma | Değerleri çarpar | `a * b` |
| `/` Bölme | Soldaki değeri sağdakine böler | `a / b` |
| `**` Üs Alma | Üs hesaplaması yapar | `a ** 2` |
| `%` Mod Alma | Bölümden kalanı döndürür | `a % b` |
| `//` Taban Bölme | Sonucu aşağıya yuvarlayarak böler | `a // b` |
"""

10//3

10%3

x = 10
y = (x//3)*3+(x%3)
print(y)

"""### Mantıksal operatörler

Mantıksal (logical) operatörler, Boolean cebirinin bir parçasıdır ve yalnızca iki değerle çalışır: `True` (1) veya `False` (0).

| Operatör | Açıklama | Örnek |
|----------|----------|--------|
| `not` | Mantıksal durumu tersine çevirir | `not a = False` → eğer `a = True` ise |
| `and` | Tüm operandlar **True** ise sonuç **True** olur | `a and b = True` → eğer `a = True` ve `b = True` ise |
| `or` | En az bir operand **True** ise sonuç **True** olur | `a or b = True` → eğer `a = True` veya `b = True` ise |

### Karşılaştırma operatörleri

Karşılaştırma (comparison) operatörleri, değerleri karşılaştırmak için kullanılır.  
Bu operatörlerin sonucu ya `True` (doğru) ya da `False` (yanlış) olur.

| Operatör | Açıklama | Örnek |
|----------|----------|--------|
| `<`  | Küçüktür             | `a < b`     |
| `<=` | Küçük eşittir        | `a <= b`    |
| `>`  | Büyüktür              | `a > b`     |
| `>=` | Büyük eşittir        | `a >= b`    |
| `==` | Eşittir              | `a == b`    |
| `!=` | Eşit değildir        | `a != b`    |

Mantıksal operatörleri çoğu zaman farkında olmadan doğal şekilde kullanırız.
Örneğin sözlü olarak şöyle dediğimizde:
“Vizesi 50’nin altında olan öğrencilerin notlarını getir”,
bunu koda şöyle çevirebiliriz:

```yeni_data = data[data["vize"] < 50]```
"""

a = 6
b = 7
print(1, a == 6)
print(2, a == 7)
print(3, a == 6 and b == 7)
print(4, a == 7 and b == 7)
print(5, not a == 7 and b == 7)
print(6, a == 7 or b == 7)
print(7, a == 7 or b == 6)
print(8, not (a == 7 and b == 6))
print(9, not a == 7 and b == 6)

"""---

## Koşullu İfadeler ve Döngüler

### 🔹 If (Eğer) İfadesi

Koşullu ifadelerde, mantıksal bir sonuca göre programın nasıl ilerleyeceğine karar veririz.  
Aşağıdaki örnekte, `r` değişkeninde tutulan değerin belirli bir eşik değerinden büyük olup olmadığını kontrol ediyoruz.  
Sonuca göre farklı işlemler yapılabilir — yani programın sonraki adımlarını `r` değişkeninin değerine göre şartlandırmış oluruz.

---

### Temel `if` Yapısı:

```python
if koşul:
    işlem1  # koşul True ise çalıştırılır
else:
    işlem2  # koşul False ise çalıştırılır
    
```

Not: Her zaman if ve else'den sonra : (iki nokta) koymayı unutmayın!


"""

r = 2.5
if r > 2.4:
    bilgi = "daha büyük"
elif r == 2.4:
    bilgi = "eşit"
else:
    bilgi = "daha küçük"
print('vaziyet:', bilgi)

"""## Döngüler: `for` Döngüsü

Bazen aynı analizi tekrar tekrar yapmak isteyebilirsiniz.  
Örneğin farklı veri setleriniz var ve her biri üzerinde analiz yapmak istiyorsunuz.

Bunu yapmak için `for` döngüsünü kullanabilirsiniz.
"""

x = [1,2,3]

for i in x:
    print(i)

for i in range(1,10,1):
    print(i,"'in karesi, ", i**2,"dir.")

"""Yerleşik `range(başlangıç, bitiş, adım)` ifadesi, artan veya azalan sayılardan oluşan bir liste döndürür.

"""

for i in range(10):
    print(i,"'in karesi, ", i*i,"dir.")

my_list = [0,3,5,4,2,7]

for i in range(len(my_list)):
    j = my_list[i]
    print(j,"'nin karesi, ", j*j,"dir.")

"""### Alıştırmalar

1- Bir sayı dizisindeki çift ve tek sayıların sayısını hesaplayan bir Python programı yazın.

```python
örnek_liste = [2, 3, 4, 5, 8, 2, 9]
"""

örnek_liste = [2, 3, 4, 5, 8, 2, 9, 5.2]

çift_sayılar = []
tek_sayılar = []

for i in örnek_liste:
    if i%2==0:
        çift_sayılar.append(i)
    elif i%2==1:
        tek_sayılar.append(i)

print(len(çift_sayılar), len(tek_sayılar))

"""2- 0 ile 50 arasındaki Fibonacci dizisini bulan bir Python programı yazın.

İpucu: Fibonacci Dizisi şu şekildedir:  
0, 1, 1, 2, 3, 5, 8, 13, 21, ...  
Her bir sonraki sayı, kendisinden önceki iki sayının toplamıdır.

"""

fib = [0, 1]

for i in range(48):
    yeni_eleman = fib[-1] + fib [-2]
    fib.append(yeni_eleman)

len(fib)

fib = [0, 1]

for i in range(100000000):
    yeni_eleman = fib[-1] + fib [-2]
    if yeni_eleman>50:
        break
    fib.append(yeni_eleman)

fib

"""3- Bunlar "liste" alıştırmalarıdır. Bu alıştırmaları **if ifadeleri** ve **döngüler** kullanarak çözün:

3.a. Bir listedeki tüm öğelerin toplamını hesaplayan Python programı yazın.

3.b. Bir listedeki en büyük ve en küçük sayıyı bulan Python programı yazın.

3.c. 10'dan küçük tamsayılardan oluşan bir liste oluşturun ve adını `a` koyun.

"""

x = [1,3,15,6]

toplam = 0

for i in x:
    toplam = toplam + i

print(toplam)

minim = x[0]

for i in x:
    if i<minim:
        minim = i

minim

my_list = []

for i in range(10):
    my_list.append(i)

print(my_list)

"""### `While` Döngüsü"""

i = 0
while i<5:
    i=i+1
    print(10*i)

"""## Girdiler (Inputs)"""

my_input = input()

type(my_input)

print("İsmin nedir?")
isim = input()
print("Kaç yaşındasın?")
yaş = float(input()) # Float fonksiyonu olmasaydı?
print ("Boyun ne kadar?")
boy = float(input())
print ("Kaç kilosun?")
kilo = float(input())

print ("Öyleyse sevgili %s, sen %f yaşındasın, boyun %f ve ayrıca %f kilosun." % (isim, yaş, boy, kilo))

"""## Fonksiyonlar

Fonksiyon, belirli bir görevi yerine getirmek için yazılmış kod parçasıdır.  
Örneğin, bir dizi değerin ortalamasını hesaplayan bir fonksiyon yazmak gibi.

Fonksiyonlar programlamada çok faydalıdır çünkü bir kere yazılır ve sonsuz kere kullanılabilirler.  
Verimli fonksiyon yazmayı öğrenmek, programlamayı lego oynamaya benzetir:  
Karmaşık bir problemi çözmek için onu parçalara ayırırız ve her parça için bir fonksiyon yazarız.  
Sonunda bu fonksiyonları lego blokları gibi birleştirerek problemi çözeriz.
"""

def greeting(name):
    output = 'Merhaba' + name
    return output

print(greeting('Fuat'))

def greeting(name):
    """Bir kullanıcıyı karşılamaya yarayan bir
    fonksiyondur."""
    message = "Merhaba " + name
    message = message + " Hoşgeldin, ne iyi ettin de geldin!"
    return message
print(greeting('Fuat'))

"""---

### Fonksiyonun Temel Bileşenleri

- **Fonksiyon Başlığı (Function Header)**  
Fonksiyon, `def` anahtar kelimesi ile başlar, ardından fonksiyonun adı ve parantez içinde aldığı parametreler (argümanlar) gelir.  
Örneğin, önceki örnekte fonksiyonun adı `greeting`, parametresi ise `name` idi.

- **Fonksiyon Dokümantasyonu (Docstring)**  
Fonksiyonun ne yaptığını açıklamak için kullanılır.  
Genellikle `'''üç tırnak işareti'''` ile yazılır.

- **Fonksiyon Gövdesi (Function Body)**  
Fonksiyonun yaptığı işlemler buraya yazılır.  
Fonksiyon çağrıldığında bu kısım çalıştırılır.

- **Return İfadesi (Return Statement)**  
Fonksiyondan çıkmak ve isteğe bağlı olarak bir değer döndürmek için kullanılır.  
`return` ifadesi olmadan fonksiyon `None` döndürür.  

---

**Örnek** 'a' and 'b' şeklinde iki girdi alan ve bunların toplamını veren bir fonksiyon yazın.
"""

def iki_sayıyı_toplama(a,b):
    """İki sayının toplamını
    döndürür."""
    return a + b

print(iki_sayıyı_toplama(4,10))

"""### Alıştırmalar (Fonksiyonlar)

1- Üç sayının en büyüğünü bulan bir Python fonksiyonu yazın.

İpucu: Önce iki sayının en büyüğünü bulan bir fonksiyon yazın.  
Daha sonra bu fonksiyonu kullanarak üç sayının en büyüğünü bulun.
"""

def maxim(a,b,c):
    return max(a, b, c)

print(maxim(3,18,9))

def maxim(a,b,c):
    if a >= b & a >= c:
        return a
    elif b > a & b > c:
        return b
    else:
        return c

print(maxim(3,18,9))

"""2- Bir listedeki tüm sayıların çarpımını hesaplayan bir Python fonksiyonu yazın.

İpucu: Bir `for` döngüsü kullanın.

```python
örnek_liste = [8, 2, 3, -1, 7]

"""

def çarpma(my_list):

    çarpan = 1

    for i in my_list:
        çarpan = çarpan * i

    return çarpan

örnek_liste = [8, 2, 3, -1, 7]

print(çarpma(örnek_liste))

"""3- Bir liste alan ve bu listenin benzersiz (unique) elemanlarından oluşan yeni bir liste döndüren Python fonksiyonu yazın.

İpucu 1: `for` döngüsü ve `if` ifadesini birlikte kullanın.  
İpucu 2: `count()` metodu, bir listede belirli bir elemanın kaç kez geçtiğini sayar.

```python
örnek_liste = [1,1,3,3,3,3,4,4,4,5,7,7,7]
# Beklenen çıktı:
benzersiz_liste = [1, 3, 4, 5, 7]

"""

def benzersiz_yapma(bir_liste):
    return list(set(bir_liste))

örnek_liste = [1,1,3,3,3,3,4,4,4,5,7,7,7]
print(benzersiz_yapma(örnek_liste))

def benzersiz(x):
    kopya_liste = x.copy()      # listeyi kopyala (dinamik olarak değiştireceğiz)
    benzersiz_liste = []        # sonucu tutacak liste

    for eleman in x:            # x içindeki her eleman için
        if kopya_liste.count(eleman) > 1:   # eleman 1'den fazla kez geçiyorsa
            kopya_liste.remove(eleman)      # bir tanesini sil
        else:                                # sadece 1 kez geçiyorsa
            benzersiz_liste.append(eleman)  # sonuca ekle

    return benzersiz_liste

örnek_liste = [1,1,3,3,3,3,4,4,4,5,7,7,7]

print(benzersiz(örnek_liste))

"""4- Bir sayı parametresi alan ve sayının asal olup olmadığını kontrol eden bir Python fonksiyonu yazın.

İpucu:  
Asal sayı, 1’den büyük ve kendisi ile 1 dışında pozitif böleni olmayan doğal sayıdır.

"""

def asal_mi(x):
    asal_mi = True

    if type(x) == float or x <= 1:   # x float ise veya 1'den küçük/eşitse
        asal_mi = "Tanımsız"
    else:
        for i in range(2, x):        # 2'den x-1'e kadar dene
            if x % i == 0:           # tam bölünüyorsa
                asal_mi = False
                break

    return asal_mi

print(asal_mi(5.3))

"""## Dosyalar"""

# dosya adını tanımla
filename = 'example.txt'

# dosyayı yazma modunda oluştur ve aç. 'w' = write (yazma) modu.
f = open(filename, 'w')

f.write("6 words story:\n")
f.write("For sale: baby shoes, never worn.")

f.close()

"""---

Yukarıdaki örneği çalıştırdığımızda, `"example.txt"` adlı bir dosya oluşturulur.  
Bu dosyada iki satır metin bulunur:  
- İlk satır: `6 words story`  
- İkinci satır: `'For sale: baby shoes, never worn.'`

Şimdi, az önce oluşturduğumuz bu dosyayı okuyalım:

"""

# dosya adını tanımla
filename = "example.txt"

# dosyayı okuma modunda aç. 'r' = read (okuma) modu.
f = open(filename, 'r')

# dosyanın içeriğini oku
data = f.read()

# dosyayı kapat
f.close()

print(data)

len(data)

data.splitlines()

"""
- İkinci satırdaki kelime sayısını sayın (gerçekten 6 kelime mi?)."""

ikinci_satır = data.splitlines()[1]
print(ikinci_satır)

ikinci_satırdaki_kelimeler = ikinci_satır.split(' ')
print(ikinci_satırdaki_kelimeler)
# print the number of words
print(len(ikinci_satırdaki_kelimeler))